/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Issue 3269 - Nullable anyOf $ref + tags-split + msw
 * OpenAPI spec version: 0.0.1
 */
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { Widget } from '../model';

export const getGetWidgetMockHandler = (
  overrideResponse?:
    | Widget
    | null
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Widget | null> | Widget | null),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/widgets',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : undefined,
        { status: 200 },
      );
    },
    options,
  );
};

export const getCreateWidgetMockHandler = (
  overrideResponse?:
    | Widget
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Widget> | Widget),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/widgets',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : undefined,
        { status: 201 },
      );
    },
    options,
  );
};
export const getWidgetsMock = () => [
  getGetWidgetMockHandler(),
  getCreateWidgetMockHandler(),
];
