/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Enums Inline
 * Test spec with inline (dereferenced) enum properties
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { User } from '../model';

export const getGetUserMockHandler = (
  overrideResponse?:
    | User
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<User> | User),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/user',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : undefined,
        { status: 200 },
      );
    },
    options,
  );
};
export const getUserMock = () => [getGetUserMockHandler()];
